### ISSUE TITLE
Slight incompatibility with Cheerio regarding doctypes

### ISSUE THREAD

**Issue by cvrebert** [inikulin/whacko#13]
Whacko(/Parse5 (?)) strips out `SYSTEM` when parsing the HTML5 [doctype legacy string](https://html.spec.whatwg.org/multipage/syntax.html#doctype-legacy-string); Cheerio doesn't:
```
$ node
> require('cheerio').load('<!DOCTYPE html SYSTEM "about:legacy-compat"><html><head></head><body>Hi there!</body></html>')(':root')[0].prev.data 
'!DOCTYPE html SYSTEM "about:legacy-compat"'
> require('whacko').load('<!DOCTYPE html SYSTEM "about:legacy-compat"><html><head></head><body>Hi there!</body></html>')(':root')[0].prev.data 
'!DOCTYPE html "about:legacy-compat"'
```
Versions I'm using:
* cheerio@0.18.0
* whacko@0.17.4

**Comment by inikulin** [comment]
It's actually a bug in parse5's htmlparse2 tree adapter. Reopening bug there.
