### ISSUE TITLE
Slow speed compared to "normal" cheerio

### ISSUE THREAD

**Issue by hofmeister** [inikulin/whacko#14]
Just did a benchmark comparison of a yelp detail page - between whacko and cheerio:

http://www.yelp.com/biz/streets-of-london-salon-chicago-2

Cheerio: ~25 ms
Whacko: ~130 ms

Test was performed using the following (just replace whacko with cheerio - since they share API)

```
var cheerio = require('whacko');
var fs = require('fs');
var pages = 100;
var content = fs.readFileSync('yelp_details.html').toString();
var startTime = Date.now();
for(var i = 0; i < pages; i++) {
	cheerio.load(content);
}

var diff = Date.now() - startTime;
console.log('Completed in %s ms ( %s ms / page ) ',diff, diff / pages );
```

Just posting this issue as a FYI - feel free to close, remove etc.

This was done on a Macbook Pro Late 2013 Retina with 16 gb mem and 2,3 Ghz i7

**Comment by inikulin** [comment]
Hello, can you make comparison using high-resolution timer and statistically valuable methodology? E.g. using [benchmark.js](http://benchmarkjs.com/)? BTW, whacko should be a little bit slower than cheerio, because it's parsing alogrithm is significantly more complcated, however x5 difference.
