### ISSUE TITLE
repository URL in package.json is wrong

### ISSUE THREAD

**Issue by cvrebert** [inikulin/whacko#9]
It currently links to http://github.com/MatthewMueller/cheerio (which just redirects to https://github.com/cheeriojs/cheerio !) instead of to this repository (https://github.com/inikulin/whacko).

**Comment by cvrebert** [comment]
Thank you!

**Comment by inikulin** [comment]
You are welcome! Seems like you are using whacko, therefore do you need location info functionality in it? Right now there is no way to enable it in whacko.

**Comment by cvrebert** [comment]
I'm not using whacko currently, just investigating; location info would be a prerequisite to switching though.
I'm surprised at the number of changes whacko had to make to cheerio, considering that parse5 already has that htmlparser2-compatible tree adapter...
Also, might be time to pull in upstream's changes again? "288 commits behind cheeriojs:master"..

**Comment by inikulin** [comment]
Seems like something wrong with the git statistics, the changes are not that complex.
It would be awesome to get rid of this fork. I've suggested Cheerio maintainers to switch to parse5 about a year and half ago. But they declined this idea ([related discussion](https://github.com/cheeriojs/cheerio/issues/247)).
